### ISSUE TITLE
v20 download 

### ISSUE THREAD

**Issue by JuiP** [sugarlabs/paths#6]
v20 is not available as .tar.bz2 file on https://download.sugarlabs.org/sources/honey/Paths/

**Comment by JuiP** [comment]
@quozl I noticed other activities also have similar issue. Is this an issue or GitHub is maintained for activity releases and the website is not actively maintained?

**Comment by quozl** [comment]
Thanks for asking.

You will see from our [maintainer checklist](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#checklist---maintainer) a number of steps.  Some steps are optional.  Some are mandatory.  Some are unclear.

We have many maintainers.  Some maintainers have done some of the steps and not others.  An oversight.  As a volunteer driven open source project, we don't punish them, we just encourage them to do better.  But some maintainers don't have the skills to do some steps.

In this case, you detected that @walterbender in releasing v20 on activities.sugarlabs.org did not upload the source.  I've just done this;

```log
git checkout v20
python setup.py dist_source
rsync -a dist/Paths-20.tar.bz2 sunjammer:/upload/sources/honey/$A/
git checkout master
```

And the issue is [solved](https://download.sugarlabs.org/sources/honey/Paths/?C=M;O=D).

**Comment by quozl** [comment]
p.s. and I'm negligent now in not checking every possible activity for this scenario.  :grinning:  Just don't have time.

**Comment by JuiP** [comment]
That seems pretty easy to get done and I feel it takes less effort to get it done than raise issues :)

Will I be able to get that done, running similar commands or do I require permissions to upload to the website?
And I do understand that only the python 2 versions are upoloaded and released on activities.sugarlabs.org , any specific reasons to not have both python 2 and python 3 ported activities on the same website? @quozl

**Comment by quozl** [comment]
> Will I be able to get that done, running similar commands or do I require permissions to upload to the website?

Permissions required are (a) an [account on shell.sugarlabs.org](https://wiki.sugarlabs.org/go/Service/shell), and (b) membership of the system group `sugardl`, which includes (among others) @chimosky, @walterbender, @tchx84, and @quozl.   We delegate the former if someone generates too many releases for our liking.  We delegate the latter if we became loaded down with "please move this file" requests.  Both are rare.

> only the python 2 versions are up<s>o</s>loaded and released on activities.sugarlabs.org

Yes, because there's up to three million laptops out there which download activities from that source, and Sugar Labs reputation would suffer greatly if we started pushing out activities that don't work.  The laptops haven't been upgraded to Python 3.  The actual number of laptops is likely to be down in the hundreds of thousands now as they have nearly reached their end of service life.  They already reached their end of production life within a few years of being made.

> reasons to not have both python 2 and python 3 ported activities on the same website?

I don't understand the question.  I'll take a punt by explaining.

For download.sugarlabs.org the .tar.bz2 files are provided as original download locations for open source licensing, without having to rely on GitHub to host the download files.  (GitHub hosts our git repositories, the commits are tagged, and so GitHub can generate a .tar.gz on the fly, but moving a tag would change the .tar.gz contents without changing the version, and downstreams hate that).

Some downstreams have scripts that watch our download.sugarlabs.org directories for new releases, and then send reminders to their teams.  By downstreams I'm talking about Fedora, Debian, and OLPC, among others.

Some activities, especially those included in OLPC OS, are maintained at the same time as Python 3 in the _master_ branch, and Python 2 in a _python2_ branch, with patches being ported between them.

We use minor versioning for maintaining old branches.  Check out the [Browse activity README.md](https://github.com/sugarlabs/browse-activity/blob/master/README.md) branches and versions list, and compare against the [download directory in reverse date order](http://download.sugarlabs.org/sources/sucrose/fructose/Browse/?C=M;O=D).

When a release of an activity happens, the steps vary according to the branch.

So literally, the reasons to have both Python 2 and Python 3 ported activities on the same web site are so that they are on a web site. :grin:

And for activities.sugarlabs.org, the reason is "don't make kids cry."

**Comment by JuiP** [comment]
> And for activities.sugarlabs.org, the reason is "don't make kids cry."

:joy: :joy: I wouldn't!

Thanks a lot! It actually cleared all my doubts :)
